### ISSUE TITLE
Issue with connecting to BOSH

### ISSUE THREAD

**Issue by allomov** [enaml-ops/omg-product-bundle#29]
I've update omg-product-bunbdle to the latest v1.0.8 version and got the error. The values which are stored in vault are correct and can be used to connect to BOSH.

```
root@19429440-7387-46a6-74cf-f88e1744aa3e:/tmp/build/1566bc7b# ./concourse-deploy-p-mysql/ci/tasks/generate-p-mysql-manifest.sh
+ chmod +x omg-cli/omg-linux
+ omg-cli/omg-linux register-plugin -type product -pluginpath omg-product-bundle/p-mysql-plugin-linux
++ vault read -field=bosh-url secret/p-mysql-nonprod-wdc1-props
++ vault read -field=bosh-port secret/p-mysql-nonprod-wdc1-props
++ vault read -field=bosh-user secret/p-mysql-nonprod-wdc1-props
++ vault read -field=bosh-pass secret/p-mysql-nonprod-wdc1-props
+ omg-cli/omg-linux deploy-product --bosh-url http://x.x.x.x --bosh-port 25555 --bosh-user admin --bosh-pass ... --ssl-ignore --print-manifest p-mysql-plugin-linux --stemcell-ver 3232.17 --vault-domain http://x.x.x.x:8200 --vault-hash-ert secret/cf-nonprod-wdc1-password --vault-hash-ert secret/cf-nonprod-wdc1-props --vault-hash-mysql-ip secret/p-mysql-nonprod-wdc1-props --vault-hash-mysql-secret secret/p-mysql-nonprod-wdc1-password --vault-token ....

2017/02/15 02:40:14 C0215 02:40:14.914114 775 bosh.go:46] Couldn't create bosh client: invalid character '<' looking for beginning of value
panic: Couldn't create bosh client:invalid character '<' looking for beginning of value

goroutine 1 [running]:
panic(0x941740, 0xc42021a130)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/enaml-ops/omg-cli/vendor/github.com/op/go-logging.(*Logger).Panic(0xc420014930, 0xc4203540c0, 0x2, 0x2)
        /go/src/github.com/enaml-ops/omg-cli/vendor/github.com/op/go-logging/logger.go:188 +0xd0
github.com/enaml-ops/omg-cli/bosh.getBoshClient(0xc42014b8e0, 0x0)
        /go/src/github.com/enaml-ops/omg-cli/bosh/bosh.go:46 +0x2f4
github.com/enaml-ops/omg-cli/bosh.ProductAction(0xc42014b8e0, 0x7f1a42797000, 0xc420328008, 0x4, 0xc420328008)
        /go/src/github.com/enaml-ops/omg-cli/bosh/bosh.go:81 +0x43
github.com/enaml-ops/omg-cli/utils.GetProductCommands.func1(0xc4202d3260, 0x0, 0x0)
        /go/src/github.com/enaml-ops/omg-cli/utils/utils.go:65 +0xcb
github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli%2ev2.(*Command).Run(0xc42014e300, 0xc42014b8e0, 0x0, 0x0)
        /go/src/github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli.v2/command.go:143 +0x787
github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli%2ev2.(*App).RunAsSubcommand(0xc4202ca000, 0xc42014b440, 0x0, 0x0)
        /go/src/github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli.v2/app.go:338 +0xa3b
github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli%2ev2.(*Command).startApp(0xc42014ee00, 0xc42014b440, 0xa691a0, 0xc41fff5a55)
        /go/src/github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli.v2/command.go:223 +0x686
github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli%2ev2.(*Command).Run(0xc42014ee00, 0xc42014b440, 0x0, 0x0)
        /go/src/github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli.v2/command.go:66 +0xc70
github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli%2ev2.(*App).Run(0xc420178420, 0xc42000c1c0, 0x1b, 0x1c, 0x0, 0x0)
        /go/src/github.com/enaml-ops/omg-cli/vendor/gopkg.in/urfave/cli.v2/app.go:228 +0x5de
main.main()
        /go/src/github.com/enaml-ops/omg-cli/main.go:165 +0x1127
```

**Comment by allomov** [comment]
the issue was that I specified http instead of https in `bosh-url`.
